### PR TITLE
Camel version bump to 2.22.2 #31

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Review by apupier — CHANGES_REQUESTED** [review]
the issue number in the commit message is #31 and not 188 188 is the issue in camel-language-server tracker, not camel-tooling-common

**Comment by lhein** [comment]
there is no issue in this repo, just in the server repo. As we share the same project board over all repos I thought thats fine.

**Comment by apupier** [comment]
> there is no issue in this repo

there is an issue in this repo https://github.com/camel-tooling/camel-tooling-common/issues/31

**Comment by lhein** [comment]
my fault. fixed.

**Review by apupier — APPROVED** [review]

**Pull request merged**
