### PR TITLE
added compiler argument -Werror camel-tooling/camel-language-server#188

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Review by apupier — CHANGES_REQUESTED** [review]
the issue number is not correct as 188 is for the camel-language-server repo, not the camel-tooling-common

**Comment by lhein** [comment]
Yes...we share the project board between the repos and there is currently no issue for that in this repo.

**Comment by apupier** [comment]
> we share the project board between the repos and there is currently no issue for that in this repo.

the board is shared but the commit message will lead to the wrong issue so that's erroneous. A new issue needs to be created and referenced or need to find a way to reference an issue from another repo

**Comment by apupier** [comment]
> need to find a way to reference an issue from another repo

seems possible using username/repository# syntax https://help.github.com/articles/autolinked-references-and-urls/

**Comment by lhein** [comment]
fixed

**Review by apupier — APPROVED** [review]

**Pull request merged**
